### ISSUE TITLE
TclError: cannot use geometry manager grid inside ...

### ISSUE THREAD

**Issue by biohegedus** [ELELAB/xpyder#3]
Hi,

I installed xpyder as root.
Installed the plugin running pymol as root.
Restart, running as root, I got the error below when I want to load the plugin.

Thanks for your help,
Tamas

cPlot: Ready...
cPlot: Selection changed to all
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pmg_tk/startup/xPyder.py", line 77, in runCPlotTk
    cPlotTk(s)
  File "/usr/lib/python2.7/dist-packages/pmg_tk/startup/xPyder.py", line 2528, in __init__
    self.table.grid(column=0, row=0, sticky='nsew')
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2022, in grid_configure
    + self._options(cnf, kw))
TclError: cannot use geometry manager grid inside .140077997030000.140077997031368.140077996744000.140078278725360.140078278406944.140078278407088.140078278407160.140078278407304.140078278407448.140078278407592 which already has slaves managed by pack

**Comment by biohegedus** [comment]
I also tried pymol 1.4.1 and got the same error.
