### ISSUE TITLE
problem of xPyder in Linux

### ISSUE THREAD

**Issue by albumns** [ELELAB/xpyder#4]
I have installed xPyder for PYMOL in my linux OS. However, when I try to
start it up, it always failed with the following information:

Traceback (most recent call last):
   File "/soft/pymol/Pymol-script-repo/xPyder.py", line 77, in runCPlotTk
     cPlotTk(s)
   File "/soft/pymol/Pymol-script-repo/xPyder.py", line 2528, in __init__
     self.table.grid(column=0, row=0, sticky='nsew')
   File "/soft/conda2/lib/python2.7/lib-tk/Tkinter.py", line 2028, in
grid_configure
     + self._options(cnf, kw))
TclError: cannot use geometry manager grid inside
.47831561802528.47831561802024.47831562950848.47831566574440.47831566817544.47831566817688.47831566817760.47831566817904.47831566818048.47831566818192
which already has slaves managed by pack

Do you have any idea how to solve this problem?

Thanks a lot

**Comment by elenapapaleo** [comment]
We should be able to release a version with this issue fixed ASAP.
